version: '3'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 582676da
      POSTGRES_DB: deploy


  nginx:
    container_name: web
    depends_on:
     - db
    image: daniloarodrigues/nginxtrans:latest
    ports:
     - "7070:80"
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 582676da