# Generated by Django 2.0.3 on 2018-04-20 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('inicio_data', models.DateField(default=None)),
                ('fim_data', models.DateField(default=None)),
                ('ano', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('criado_em', models.DateField(default=datetime.datetime(2018, 4, 20, 14, 49, 13, 234588, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Contratos',
                'ordering': ('numero',),
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('numero', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('contrato', models.CharField(default=None, max_length=10)),
                ('objeto', models.TextField()),
                ('ano', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('criado_em', models.DateField(default=datetime.datetime(2018, 4, 20, 14, 49, 13, 236298, tzinfo=utc), verbose_name='Data de abertura')),
                ('arquivos', models.ManyToManyField(blank=True, default=None, null=True, to='licitacao.Arquivo')),
            ],
            options={
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('ano', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('criado_em', models.DateField(default=datetime.datetime(2018, 4, 20, 14, 49, 13, 233973, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Processos',
                'ordering': ('numero',),
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('criado_em', models.DateField(default=datetime.datetime(2018, 4, 20, 14, 49, 13, 232837, tzinfo=utc))),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='processo',
            unique_together={('ano', 'numero')},
        ),
        migrations.AddField(
            model_name='modalidade',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licitacao.Processo'),
        ),
        migrations.AddField(
            model_name='modalidade',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacao.Situacao'),
        ),
        migrations.AddField(
            model_name='modalidade',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacao.Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('ano', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='modalidade',
            unique_together={('ano', 'tipo', 'numero')},
        ),
    ]
