# Generated by Django 2.0.3 on 2018-04-13 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('licitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 13, 18, 14, 56, 356590, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 13, 18, 14, 56, 357358, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='processo',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 13, 18, 14, 56, 355890, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 13, 18, 14, 56, 355299, tzinfo=utc)),
        ),
    ]
