# Generated by Django 2.0.3 on 2018-04-13 18:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('licitacao', '0002_auto_20180413_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 13, 18, 26, 51, 301392, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 13, 18, 26, 51, 302136, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='processo',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 13, 18, 26, 51, 300759, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 13, 18, 26, 51, 300177, tzinfo=utc)),
        ),
    ]
