# Generated by Django 2.0.3 on 2018-04-14 00:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('licitacao', '0003_auto_20180413_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 14, 0, 53, 14, 826081, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 14, 0, 53, 14, 826830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='processo',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 14, 0, 53, 14, 825440, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 14, 0, 53, 14, 824855, tzinfo=utc)),
        ),
    ]
