# Generated by Django 2.0.3 on 2018-04-14 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('licitacao', '0004_auto_20180413_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 14, 20, 34, 21, 394210, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 14, 20, 34, 21, 394963, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='processo',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 14, 20, 34, 21, 393378, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2018, 4, 14, 20, 34, 21, 392709, tzinfo=utc)),
        ),
    ]
