# Generated by Django 2.0.3 on 2018-04-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('logo', models.ImageField(upload_to='')),
                ('cnpj', models.IntegerField()),
                ('rua', models.CharField(max_length=80)),
                ('numero', models.PositiveIntegerField()),
                ('bairro', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=80)),
                ('cep', models.PositiveIntegerField()),
                ('telefone', models.PositiveIntegerField()),
            ],
        ),
    ]
